-- MySQL Script generated by MySQL Workbench
-- 06/10/15 15:11:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema camelus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema camelus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `camelus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `camelus` ;
-- -----------------------------------------------------
-- Table `camelus`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`admins` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `hire_date` VARCHAR(45) NOT NULL,
  `sin` INT(9) NOT NULL,
  `superadmin` TINYINT(1) NULL DEFAULT 0,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camelus`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camelus`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `upc` VARCHAR(12) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `unit_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `img_url` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `FK_PRODUCTS_UNITS_ID_idx` (`unit_id` ASC),
  CONSTRAINT `FK_PRODUCTS_UNITS_ID`
    FOREIGN KEY (`unit_id`)
    REFERENCES `camelus`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `camelus`.`commissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`commissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT(1) NOT NULL,
  `rate` INT NOT NULL,
  `condition` INT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camelus`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`vendors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `hire_date` VARCHAR(45) NOT NULL,
  `sin` INT(9) NOT NULL,
  `commission_id` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `FK_EMPLOYEES_COMMISSIONS_ID_idx` (`commission_id` ASC),
  CONSTRAINT `FK_VENDORS_COMMISSIONS_ID`
    FOREIGN KEY (`commission_id`)
    REFERENCES `camelus`.`commissions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `camelus`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`clients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `enterprise_name` VARCHAR(45) NOT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `contact_tel` VARCHAR(45) NOT NULL,
  `contact_email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `camelus`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `vendor_id` BIGINT NOT NULL,
  `client_id` BIGINT NOT NULL,
  `comment` VARCHAR(255) NULL,
  `ordered_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `FK_ORDERS_CLIENTS_ID_idx` (`client_id` ASC),
  INDEX `FK_ORDERS_VENDORS_ID_idx` (`vendor_id` ASC),
  CONSTRAINT `FK_ORDERS_CLIENTS_ID`
    FOREIGN KEY (`client_id`)
    REFERENCES `camelus`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORDERS_VENDORS_ID`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `camelus`.`vendors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `camelus`.`order_lines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `camelus`.`order_lines` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL,
  `order_id` BIGINT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `modified_price` DECIMAL(10,2) NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ORDERLINES_PRODUCTS_ID_idx` (`product_id` ASC),
  INDEX `FK_ORDERLINES_ORDERS_ID_idx` (`order_id` ASC),
  CONSTRAINT `FK_ORDERLINES_PRODUCTS_ID`
    FOREIGN KEY (`product_id`)
    REFERENCES `camelus`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ORDERLINES_ORDERS_ID`
    FOREIGN KEY (`order_id`)
    REFERENCES `camelus`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
